apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 31400
      name: tcp
      protocol: TCP
    hosts:
    - {{ include "explorviz.hostUrl" . | quote }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ include "explorviz.hostUrl" . | quote }}
