apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway-{{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31400
      name: tcp{{ .Release.Namespace }}
      protocol: TCP
    hosts:
    - {{ include "explorviz.hostUrl" . | quote }}
  - port:
      number: 50051
      name: grpc{{ .Release.Namespace }}
      protocol: GRPC
    hosts:
    - {{ include "explorviz.hostUrl" . | quote }}
  - port:
      number: 80
      name: http{{ .Release.Namespace }}
      protocol: HTTP
    hosts:
    - {{ include "explorviz.hostUrl" . | quote }}
