apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}{{ .Release.Namespace }}-ingress
  namespace: istio-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ include "explorviz.hostUrl" . | quote }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80
