apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtual-service
spec:
  hosts:
  - {{ include "explorviz.hostUrl" . | quote }}
  gateways:
  - {{ .Release.Namespace }}/{{ .Release.Name }}-gateway-{{ .Release.Namespace }}
  tcp:
  - match:
    - port: 31400
    route:
    - destination:
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.landscapeService) }}
        port:
          number: 9000
  http:
  - match:
    - port: 50051
    route:
    - destination:
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.grpcService) }}
        port:
          number: 50051
  - match:
    - uri:
        prefix: "/v1/tokens"
    - uri:
        prefix: "/v1/users"
    - uri:
        prefix: "/v1/roles"
    - uri:
        prefix: "/v1/userbatch"
    route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.userService) }}
  - match:
    - uri:
        prefix: "/v1/settings"
    - uri:
        prefix: "/v1/preferences"
    route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.settingsService) }}
  - match:
    - uri:
        prefix: "/v1/landscapes/broadcast"
    route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.broadcastService) }}
  - match:
    - uri:
        prefix: "/v1/landscapes"
    - uri:
        prefix: "/v1/timestamps"    
    route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.historyService) }}
  - match:
    - uri:
        prefix: "/v1/agents"
    route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.discoveryService) }}
  - route:
    - destination:
        port:
          number: 8000
        host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.frontend) }}
    # - destination:
    #     host: {{ template "explorviz.host" (dict "Release" .Release "component" .Values.grpcService) }}
    #     port:
    #       number: 50051