# Default values for explorviz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

port: 80
grpcPort: 50051
monitoringPort: 8060

broadcastService:
  name: broadcast-service
  image: explorviz/explorviz-backend-broadcast-service:explorviz-1.5-istio
  port: 8081
  kafka:
    topic: landscape-update

userService:
  name: user-service
  image: explorviz/explorviz-backend-user-service:explorviz-1.5-istio
  port: 8082
  mongoPort: 27017
  kafka:
    topic:

discoveryService:
  name: discovery-service
  image: explorviz/explorviz-backend-discovery-service:explorviz-1.5-istio
  port: 8083

historyService:
  name: history-service
  image: explorviz/explorviz-backend-history-service:explorviz-1.5-istio
  port: 8086
  kafka:
    topic: landscape-update
  mongoPort: 27018

settingsService:
  name: settings-service
  image: explorviz/explorviz-backend-settings-service:explorviz-1.5-istio
  port: 8087
  mongoPort: 27019
  kafka:
    topic:

landscapeService:
  name: landscape-service
  image: explorviz/explorviz-backend-landscape-service:explorviz-1.5-istio
  port: 10135
  kafka:
    topic: landscape-update

grpcService:
  name: grpc-service
  image: grpc/java-example-hostname
  port: 50051
  kafka:
    topic: 

frontend:
  name: frontend
  image: explorviz/explorviz-frontend:1.5.0
  port: 80

cp-helm-charts:
  enabled: true
  cp-zookeeper:
    servers: 3
  cp-kafka:
    brokers: 3
    # customEnv:
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT"
    # configurationOverrides:
      # "advertised.listeners": |-
      #  EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})),EXTERNAL_HOST://explorviz-istio-cp-kafka-${KAFKA_BROKER_ID}.explorviz-istio-cp-kafka-headless.explorviz:$((31688 + ${KAFKA_BROKER_ID}))
  cp-schema-registry:
    enabled: false
  cp-kafka-connect:
    enabled: false
  cp-kafka-rest:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false