name: Docker Image CI

on:
  push:
    branches: 
      - master
      - github-actions
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build the jvm executables
      run: ./gradlew quarkusBuild
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: explorviz/istio-playground/jvm
        image_tag: latest
        registry: docker.pkg.github.com
        dockerfile: src/main/docker/Dockerfile.jvm
    - name: Build the native executables
      run: ./gradlew buildNative --docker-build=true
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: explorviz/istio-playground/native
        image_tag: latest
        registry: docker.pkg.github.com
        dockerfile: src/main/docker/Dockerfile.native
