name: Test local istio action

on:
  push:
    branches: 
     - istio-actions
  pull_request:
    branches: [ master ]

jobs:
  test-istio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: engineerd/setup-kind@v0.3.0
    - name: Setup istio
      uses: ./.github/actions/setup-istio # Uses an action in the root directory
      id: setup-istio

