# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test istio in Kubernetes in Docker

on:
  push:
    branches: 
     - master
     - github-actions
     - istio-actions
  pull_request:
    branches: [ master ]

jobs:
  test-istio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build the executables
      run: ./gradlew quarkusBuild
    - name: Build jvm image for local use
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker pull --all-tags docker.pkg.github.com/explorviz/istio-playground/jvm-stages || true
        docker build -f src/main/docker/Dockerfile.jvm -t docker.pkg.github.com/explorviz/istio-playground/jvm:latest .
    - uses: engineerd/setup-kind@v0.3.0
    - name: Setup istio
      uses: ./.github/actions/setup-istio
      id: setup-istio
    - id: startIstio
      name: Start istio-playground
      run: |
        kind load docker-image docker.pkg.github.com/explorviz/istio-playground/jvm:latest

        kubectl create namespace quarkus
        kubectl label namespace quarkus istio-injection=enabled

        kubectl apply -f src/main/kube/app.yaml
        kubectl apply -f src/main/kube/gateway.yaml
        kubectl apply -f src/main/kube/authentication-policy.yaml

        kubectl wait --for=condition=Ready pod --all -n quarkus --timeout=60s

        INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
        INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}')

        echo "::set-env name=gateway_url::$INGRESS_HOST:$INGRESS_PORT"
    - name: Test accessibility of pages
      run: |
        curl -s http://${{env.gateway_url}}/login.html | grep "Login page"
        curl -s http://${{env.gateway_url}}/asecret.html | grep "RBAC: access denied"

