{{ template "explorviz.service" (dict "Values" .Values "component" .Values.settingsService)  }}
{{ template "explorviz.deployment" (dict "Values" .Values "Release" .Release "component" .Values.settingsService)  }}
